# Generated by Django 4.1.7 on 2023-03-21 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garagem', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Descricao',
            new_name='Categoria',
        ),
    ]
