# Generated by Django 4.2.1 on 2023-05-09 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garagem', '0004_alter_veiculo_categoria_alter_veiculo_cor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca',
            name='modelo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
