# Generated by Django 4.2.1 on 2023-05-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garagem', '0005_marca_modelo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marca',
            name='modelo',
        ),
        migrations.AddField(
            model_name='veiculo',
            name='modelo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
